stages:
  - tag

semantic_release:
  stage: tag
  image: node:12
  variables:
      GITLAB_TOKEN: $GITLAB_TOKEN
  before_script:
      - npm install -g semantic-release @semantic-release/gitlab-config
      - npm install @semantic-release/changelog @semantic-release/git
  script:
      - semantic-release -e @semantic-release/gitlab-config
  only:
      - master