stages:
  - tag

semantic_release:
  stage: tag
  image: node:12
  variables:
      GITLAB_TOKEN: $GITLAB_TOKEN
  before_script:
      - npm install -g semantic-release @semantic-release/gitlab-config
      - touch CHANGELOG.md
      - npm install @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/npm @semantic-release/git --save-dev
  script:
      - semantic-release -e @semantic-release/gitlab-config
  artifacts:
    paths:
    - CHANGELOG.md
  only:
      - master