{
  branches: [
    {
      name: 'master'
    },
    {
      name: 'pre/rc', 
      channel: 'pre/rc', 
      prerelease: 'rc'
    },
    {
      name: 'beta', 
      channel: 'beta', 
      prerelease: 'beta'
    }
  ],
  plugins: [
    "@semantic-release/gitlab",
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/npm",
    [
      "@semantic-release/changelog",
      {
        changelogFile: "CHANGELOG.md"
      }
    ],
    [
      "@semantic-release/git",
      {
        assets: ["CHANGELOG.md"]
      }
    ]
  ],
  analyzeCommits: {
    releaseRules: [
      {
        type: "docs",
        scope: "README",
        release: "patch"
      },
      {
        type: "refactor",
        release: "patch"
      },
      {
        type: "style",
        release: "patch"
      }
    ]
  }
}